<?php
$rolRequerido = "solicitante";
require_once __DIR__ . "/../../../app/controlador/verificarAcceso.php";
verificarAcceso($rolRequerido);
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Incidencias</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/global.css"><link rel="stylesheet" href="../assets/css/formularios.css"></head>
<body class="d-flex flex-column min-vh-100 sgrsi-app"><header class="navbar navbar-dark sgrsi-navbar"><nav class="container-fluid"><a class="navbar-brand" href="inicio.php">SGRSI</a><div><a class="btn btn-link text-light" href="solicitudes.php">Solicitudes</a><a class="btn btn-link text-light" href="incidencias.php">Incidencias</a><a class="btn btn-link text-light" href="../cerrarSesion.php">Cerrar sesión</a></div></nav></header>
<main class="flex-grow-1 p-3"><section class="bg-white rounded p-4 mb-4"><h1 class="h4">Reportar incidencia</h1><form action="procesarAltaIncidencia.php" method="post" class="row g-3">
<div class="col-md-6"><label class="form-label" for="fechaApertura">Fecha de apertura</label><input class="form-control" type="datetime-local" id="fechaApertura" name="fechaApertura" required></div>
<div class="col-md-6"><label class="form-label" for="turno">Turno</label><select class="form-select" id="turno" name="turno" required><option value="">Seleccione</option><option>MATUTINO</option><option>VESPERTINO</option><option>NOCTURNO</option></select></div>
<div class="col-md-6"><label class="form-label" for="nombreDocente">Docente</label><input class="form-control" id="nombreDocente" name="nombreDocente" required></div><div class="col-md-6"><label class="form-label" for="grupo">Grupo</label><input class="form-control" id="grupo" name="grupo" required></div>
<div class="col-md-6"><label class="form-label" for="asignatura">Asignatura</label><input class="form-control" id="asignatura" name="asignatura" required></div><div class="col-md-6"><label class="form-label">¿Reportó un alumno?</label><div><label><input type="radio" name="reportoAlumno" value="SI" required> Sí</label> <label><input type="radio" name="reportoAlumno" value="NO"> No</label></div></div>
<div class="col-md-6"><label class="form-label" for="nombreAlumno">Nombre del alumno</label><input class="form-control" id="nombreAlumno" name="nombreAlumno" disabled></div><div class="col-12"><label class="form-label" for="descripcion">Descripción</label><textarea class="form-control" id="descripcion" name="descripcion" required></textarea></div><div class="col-12"><button class="btn btn-primary">Registrar incidencia</button></div></form></section>
<section class="bg-white rounded p-4"><h2 class="h4">Mis incidencias</h2><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>ID</th><th>Apertura</th><th>Grupo</th><th>Descripción</th><th>Estado</th></tr></thead><tbody><?php foreach ($incidencias as $incidencia): ?><tr><td><?= htmlspecialchars($incidencia["idIncidencia"]) ?></td><td><?= htmlspecialchars($incidencia["fechaApertura"]) ?></td><td><?= htmlspecialchars($incidencia["grupo"]) ?></td><td><?= htmlspecialchars($incidencia["descripcion"]) ?></td><td><?= htmlspecialchars($incidencia["estado"]) ?></td></tr><?php endforeach; ?></tbody></table></div></section></main>
<script>document.querySelectorAll('input[name="reportoAlumno"]').forEach(opcion=>opcion.addEventListener("change",()=>{const campo=document.getElementById("nombreAlumno");campo.disabled=opcion.value!=="SI";campo.required=opcion.value==="SI";if(campo.disabled)campo.value="";}));</script></body></html>
