ALTER TABLE PRESTAMO
    MODIFY fechaDevolucion DATETIME NOT NULL,
    ADD fechaDevolucionReal DATETIME NULL,
    ADD estado VARCHAR(10) NOT NULL DEFAULT 'ACTIVO';

UPDATE PRESTAMO
SET estado = 'ACTIVO';
